spring:
  redis:
    password: "1q2w3e4r!"

  data:
    mongodb:
      uri: mongodb://kidjjy:1q2w3e4r%21@3.35.21.90:27017/IoT?authSource=admin

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 7fd6112fa7ebf21d960c2f2a64f6d690
            client-secret: u9okpAxCFPjqkiAUWWUCCrhc4ED2uxMH
            javascript-key: "026dc65bf545cec292b6ff02dac60287"
            redirect-uri: "http://localhost:8080/kakao/callback"
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me


jwt:
  secret:
    access: "myPasswordToLongIWantToFinishMyFinalProjectWhatIsProblemInMyJwtToken"
    refresh: "myRefreshTokenIsEnoughLongRefreshTokenWhatIsProblem"

heyhome:
  token: "5edfd77b-0e73-4a99-a81a-c5d9422fcde0"

python:
#  path: "/var/www/python/venv/bin/python"
  path: "D:\\Coding\\notice\\.venv\\Scripts\\python.exe"
  code_notification_path: "/var/www/python/dash"
  code_path: "D:/Coding/notice"
#  code_one_line_path: "/var/www/python/oneAdvice"
  code_one_line_path: "D:/Coding/oneAdvice"



pdf:
  terms: "/var/www/spring/pdf/개인정보처리방침.pdf"
  #terms: "C:/pdf/개인정보처리방침.pdf"
  privacy: "/var/www/spring/pdf/서비스이용약관(자사 제품, 서비스 공급용).pdf"
  #privacy: "C:/pdf/서비스이용약관(자사 제품, 서비스 공급용).pdf"


